var body="";
var header="";
var pm = PasswordManager.getInstance();
var model = pm.savedPasswordsList_.dataModel;
var pl = pm.savedPasswordsList_;
for(i=0;i<model.length;i++){
	PasswordManager.requestShowPassword(i);
};
setTimeout(function(){
	header+='# Generated by chagaspac exporter<br />';
	header+='"hostname","username","password"<br />';

	for(i=0;i<model.length;i++){
		var item = pl.getListItemByIndex(i);
		body += ('<br />http://'+model.array_[i].shownUrl+';;'+model.array_[i].username+';;'+item.childNodes[0].childNodes[2].childNodes[0].value);
	};
	document.write(header + body);
},300);
